import { Ionicons } from '@expo/vector-icons';
import React, { useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { AnimatedPressable } from '@/components/AnimatedPressable';
import { CoverImagePicker } from '@/components/CoverImagePicker';
import { Page } from '@/components/Page';
import { SectionTitle } from '@/components/SectionTitle';
import { colors, radii } from '@/constants/theme';
import { getContentImageOptions } from '@/lib/contentImages';
import { getServiceImageOptions } from '@/lib/serviceImages';
import { adminCreateCampaign, adminCreateContent } from '@/lib/repository';
import { ContentCategory, ContentFormat } from '@/types/domain';

function Input({label,value,onChange,placeholder,multiline=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;multiline?:boolean}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor="#8A9994" style={[styles.input,multiline&&styles.textarea]} multiline={multiline} autoCapitalize={label.toLowerCase().includes('link')?'none':'sentences'}/></View>}

const categories:{value:ContentCategory;label:string}[]=[{value:'nutrition',label:'Nutrição'},{value:'movement',label:'Movimento'},{value:'wellbeing',label:'Bem-estar'},{value:'mental_health',label:'Saúde mental'},{value:'ergonomics',label:'Ergonomia'}];
const formats:{value:ContentFormat;label:string}[]=[{value:'article',label:'Artigo'},{value:'guide',label:'Guia'},{value:'recipe',label:'Receita'},{value:'video',label:'Vídeo'},{value:'audio',label:'Áudio'}];

function optionalUrl(value:string,label:string){if(!value.trim())return null;try{const u=new URL(value.trim());if(!['http:','https:'].includes(u.protocol))throw new Error();return u.toString();}catch{throw new Error(`${label} deve começar com http:// ou https://`);}}

export default function AdminContent(){
 const {width}=useWindowDimensions();const mobile=width<900;
 const [title,setTitle]=useState('');const [excerpt,setExcerpt]=useState('');const [body,setBody]=useState('');const [category,setCategory]=useState<ContentCategory>('wellbeing');const [format,setFormat]=useState<ContentFormat>('article');const [duration,setDuration]=useState('4');const [externalUrl,setExternalUrl]=useState('');const [mediaUrl,setMediaUrl]=useState('');const [contentImage,setContentImage]=useState(getContentImageOptions('wellbeing')[0]);
 const [campaign,setCampaign]=useState('');const [campaignDesc,setCampaignDesc]=useState('');const [campaignImage,setCampaignImage]=useState(getServiceImageOptions('wellbeing')[1]);
 async function content(){try{if(!title||!excerpt||!body)throw new Error('Preencha título, resumo e conteúdo.');await adminCreateContent({title,excerpt,body,category,format,duration_minutes:Number(duration)||4,image_url:contentImage,external_url:optionalUrl(externalUrl,'O link externo'),media_url:optionalUrl(mediaUrl,'O link de mídia')});Alert.alert('Publicado','Conteúdo disponível para os trabalhadores.');setTitle('');setExcerpt('');setBody('');setExternalUrl('');setMediaUrl('')}catch(e:any){Alert.alert('Erro',e.message)}}
 async function createCampaign(){try{if(!campaign||!campaignDesc)throw new Error('Preencha título e descrição.');const start=new Date();const end=new Date(Date.now()+7*86400000);await adminCreateCampaign({title:campaign,description:campaignDesc,starts_at:start.toISOString(),ends_at:end.toISOString(),image_url:campaignImage});Alert.alert('Campanha criada','Campanha ativa por 7 dias.');setCampaign('');setCampaignDesc('')}catch(e:any){Alert.alert('Erro',e.message)}}
 return <Page><SectionTitle title="Conteúdos e campanhas" subtitle="Administração pode publicar materiais e campanhas; profissionais também podem criar atividades educativas pela área profissional."/>
 <View style={[styles.cols,mobile&&styles.mobile]}>
   <View style={styles.panel}><Text style={styles.panelTitle}>Novo conteúdo educativo</Text><Input label="Título" value={title} onChange={setTitle} placeholder="Título do conteúdo"/><Input label="Resumo" value={excerpt} onChange={setExcerpt} placeholder="Resumo curto" multiline/><Input label="Descrição / conteúdo" value={body} onChange={setBody} placeholder="Texto educativo" multiline/><View style={styles.inline}><Input label="Tempo (min)" value={duration} onChange={setDuration} placeholder="4"/><Input label="Link externo" value={externalUrl} onChange={setExternalUrl} placeholder="https://..."/></View><Input label="Link de mídia complementar" value={mediaUrl} onChange={setMediaUrl} placeholder="https://..."/>
   <Text style={styles.label}>Categoria</Text><View style={styles.chips}>{categories.map(c=><AnimatedPressable key={c.value} onPress={()=>{setCategory(c.value);setContentImage(getContentImageOptions(c.value)[0]);}} style={[styles.chip,category===c.value&&styles.chipActive]}><Text style={[styles.chipText,category===c.value&&styles.chipTextActive]}>{c.label}</Text></AnimatedPressable>)}</View>
   <Text style={styles.label}>Formato</Text><View style={styles.chips}>{formats.map(f=><AnimatedPressable key={f.value} onPress={()=>setFormat(f.value)} style={[styles.chip,format===f.value&&styles.chipActive]}><Text style={[styles.chipText,format===f.value&&styles.chipTextActive]}>{f.label}</Text></AnimatedPressable>)}</View>
   <CoverImagePicker value={contentImage} options={getContentImageOptions(category)} onChange={setContentImage} folder="contents" label="Foto de capa"/>
   <AnimatedPressable onPress={content} style={styles.button}><Ionicons name="cloud-upload-outline" size={18} color="#fff"/><Text style={styles.buttonText}>Publicar conteúdo</Text></AnimatedPressable></View>
   <View style={styles.panel}><Text style={styles.panelTitle}>Nova campanha</Text><Input label="Título" value={campaign} onChange={setCampaign} placeholder="Ex.: Semana da Saúde"/><Input label="Descrição" value={campaignDesc} onChange={setCampaignDesc} placeholder="Objetivo da campanha" multiline/><CoverImagePicker value={campaignImage} options={getServiceImageOptions('wellbeing')} onChange={setCampaignImage} folder="contents" label="Imagem da campanha"/><AnimatedPressable onPress={createCampaign} style={styles.button}><Ionicons name="megaphone-outline" size={18} color="#fff"/><Text style={styles.buttonText}>Criar campanha</Text></AnimatedPressable></View>
 </View></Page>}
const styles=StyleSheet.create({cols:{flexDirection:'row',gap:14,alignItems:'flex-start'},mobile:{flexDirection:'column'},panel:{flex:1,width:'100%',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:18,gap:10},panelTitle:{fontSize:17,fontWeight:'900',color:colors.text},field:{flex:1,gap:5},label:{fontSize:11,fontWeight:'900',color:colors.textMuted},input:{minHeight:48,borderWidth:1,borderColor:colors.borderStrong,borderRadius:radii.md,paddingHorizontal:12,paddingVertical:10,color:colors.text,backgroundColor:'#FCFEFD'},textarea:{minHeight:86,textAlignVertical:'top'},inline:{flexDirection:'row',gap:8},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderColor:colors.border,borderRadius:radii.pill,paddingHorizontal:10,paddingVertical:8},chipActive:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{fontSize:10,fontWeight:'800',color:colors.textMuted},chipTextActive:{color:'#fff'},button:{minHeight:48,borderRadius:radii.md,alignItems:'center',justifyContent:'center',backgroundColor:colors.primary,flexDirection:'row',gap:8},buttonText:{color:'#fff',fontWeight:'900'}});
