import React, { useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { AnimatedPressable } from '@/components/AnimatedPressable';
import { Page } from '@/components/Page';
import { SectionTitle } from '@/components/SectionTitle';
import { colors, radii } from '@/constants/theme';
import { adminCreateCampaign, adminCreateContent } from '@/lib/repository';
function Input({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor="#8A9994" style={styles.input} multiline={label==='Corpo' || label==='Descrição'}/></View>}
export default function AdminContent(){const {width}=useWindowDimensions();const mobile=width<760;const [title,setTitle]=useState('');const [excerpt,setExcerpt]=useState('');const [body,setBody]=useState('');const [campaign,setCampaign]=useState('');const [campaignDesc,setCampaignDesc]=useState('');async function content(){try{await adminCreateContent({title,excerpt,body,category:'wellbeing',format:'article',duration_minutes:4,image_url:'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1400&q=80'});Alert.alert('Publicado','Conteúdo disponível para os trabalhadores.');setTitle('');setExcerpt('');setBody('')}catch(e:any){Alert.alert('Erro',e.message)}}async function createCampaign(){try{const start=new Date();const end=new Date(Date.now()+7*86400000);await adminCreateCampaign({title:campaign,description:campaignDesc,starts_at:start.toISOString(),ends_at:end.toISOString(),image_url:'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1400&q=80'});Alert.alert('Campanha criada','Campanha ativa por 7 dias.');setCampaign('');setCampaignDesc('')}catch(e:any){Alert.alert('Erro',e.message)}}return <Page><SectionTitle title="Conteúdos e campanhas" subtitle="Publicação institucional centralizada no perfil administrador."/><View style={[styles.cols,mobile&&styles.mobile]}><View style={styles.panel}><Text style={styles.panelTitle}>Novo conteúdo educativo</Text><Input label="Título" value={title} onChange={setTitle} placeholder="Título do conteúdo"/><Input label="Resumo" value={excerpt} onChange={setExcerpt} placeholder="Resumo curto"/><Input label="Corpo" value={body} onChange={setBody} placeholder="Texto educativo"/><AnimatedPressable onPress={content} style={styles.button}><Text style={styles.buttonText}>Publicar conteúdo</Text></AnimatedPressable></View><View style={styles.panel}><Text style={styles.panelTitle}>Nova campanha</Text><Input label="Título" value={campaign} onChange={setCampaign} placeholder="Ex.: Semana da Saúde"/><Input label="Descrição" value={campaignDesc} onChange={setCampaignDesc} placeholder="Objetivo da campanha"/><AnimatedPressable onPress={createCampaign} style={styles.button}><Text style={styles.buttonText}>Criar campanha</Text></AnimatedPressable></View></View></Page>}
const styles=StyleSheet.create({cols:{flexDirection:'row',gap:14,alignItems:'flex-start'},mobile:{flexDirection:'column'},panel:{flex:1,width:'100%',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:18,gap:10},panelTitle:{fontSize:17,fontWeight:'900',color:colors.text},field:{gap:5},label:{fontSize:11,fontWeight:'900',color:colors.textMuted},input:{minHeight:48,borderWidth:1,borderColor:colors.borderStrong,borderRadius:radii.md,paddingHorizontal:12,paddingVertical:10,color:colors.text,backgroundColor:'#FCFEFD'},button:{minHeight:48,borderRadius:radii.md,alignItems:'center',justifyContent:'center',backgroundColor:colors.primary},buttonText:{color:'#fff',fontWeight:'900'}});
