import React, { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable } from '@/components/AnimatedPressable';
import { Page } from '@/components/Page';
import { SectionTitle } from '@/components/SectionTitle';
import { colors, radii } from '@/constants/theme';
import { adminSetRole, getAdminUsers } from '@/lib/repository';
import { AdminUser, UserRole } from '@/types/domain';
const labels:Record<UserRole,string>={worker:'Trabalhador',professional:'Profissional',manager:'Gestão',admin:'Administrador'};
export default function AdminUsers(){const [users,setUsers]=useState<AdminUser[]>([]);async function load(){setUsers(await getAdminUsers())}useEffect(()=>{load()},[]);async function setRole(id:string,role:UserRole){try{await adminSetRole(id,role);await load()}catch(e:any){Alert.alert('Erro',e.message)}}return <Page><SectionTitle title="Usuários e perfis" subtitle="Controle de acesso por papel. Alterações de papel são exclusivas do administrador."/><View style={styles.list}>{users.map(u=><View key={u.id} style={styles.card}><View style={styles.avatar}><Text style={styles.avatarText}>{u.full_name.slice(0,1)}</Text></View><View style={{flex:1,minWidth:180}}><Text style={styles.name}>{u.full_name}</Text><Text style={styles.meta}>{u.unit_name||'Sem unidade'} · {u.sector||'Setor não informado'} · {labels[u.role]}</Text></View><View style={styles.roles}>{(['worker','professional','manager','admin'] as UserRole[]).map(r=><AnimatedPressable key={r} onPress={()=>setRole(u.id,r)} style={[styles.role,u.role===r&&styles.roleActive]}><Text style={[styles.roleText,u.role===r&&styles.roleTextActive]}>{labels[r]}</Text></AnimatedPressable>)}</View></View>)}</View></Page>}
const styles=StyleSheet.create({list:{gap:9},card:{flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:11,padding:14,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg},avatar:{width:42,height:42,borderRadius:14,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},avatarText:{fontWeight:'900',color:colors.primaryDark},name:{fontWeight:'900',color:colors.text},meta:{fontSize:11,color:colors.textMuted,marginTop:2},roles:{flexDirection:'row',gap:5,flexWrap:'wrap'},role:{paddingHorizontal:8,paddingVertical:7,borderRadius:radii.pill,borderWidth:1,borderColor:colors.border},roleActive:{backgroundColor:colors.primary,borderColor:colors.primary},roleText:{fontSize:9,fontWeight:'800',color:colors.textMuted},roleTextActive:{color:'#fff'}});
