import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { Page } from '@/components/Page';
import { SectionTitle } from '@/components/SectionTitle';
import { StatCard } from '@/components/StatCard';
import { AnimatedPressable } from '@/components/AnimatedPressable';
import { colors, radii } from '@/constants/theme';
import { getManagerDashboard, getManagerFilterOptions } from '@/lib/repository';
import { AttendanceMetricItem, DashboardData, ManagerFilterOptions, MetricItem } from '@/types/domain';

function MetricBars({title,items,suffix=''}:{title:string;items:MetricItem[]|AttendanceMetricItem[];suffix?:string}){
  const max=Math.max(1,...items.map(x=>x.value));
  return <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{items.length===0?<Text style={styles.empty}>Sem dados para o filtro selecionado.</Text>:items.map(x=><View key={x.label} style={styles.barRow}><Text style={styles.barLabel}>{x.label}</Text><View style={styles.barTrack}><View style={[styles.barFill,{width:`${Math.max(5,Math.round(x.value/max*100))}%`} as any]}/></View><Text style={styles.barValue}>{x.value}{suffix}</Text></View>)}</View>;
}

export default function ManagerDashboard(){
 const {width}=useWindowDimensions(); const mobile=width<760;
 const [days,setDays]=useState(30); const [unitId,setUnitId]=useState<string|null>(null); const [sector,setSector]=useState<string|null>(null);
 const [data,setData]=useState<DashboardData|null>(null); const [filters,setFilters]=useState<ManagerFilterOptions>({units:[],sectors:[]}); const [loading,setLoading]=useState(true);
 useEffect(()=>{getManagerFilterOptions().then(setFilters).catch(console.warn);},[]);
 useEffect(()=>{setLoading(true);getManagerDashboard(days,unitId,sector).then(setData).finally(()=>setLoading(false));},[days,unitId,sector]);
 const selectedUnit=useMemo(()=>filters.units.find(u=>u.id===unitId)?.name??'Todas as unidades',[filters.units,unitId]);
 return <Page><SectionTitle title="Painel gerencial" subtitle="Indicadores consolidados por período, unidade e setor para apoiar o planejamento das ações de saúde do trabalhador."/>
 <View style={styles.filterPanel}><Text style={styles.filterTitle}>Filtros</Text><Text style={styles.filterLabel}>Período</Text><View style={styles.filters}>{[7,30,90,365].map(d=><AnimatedPressable key={d} onPress={()=>setDays(d)} style={[styles.filter,days===d&&styles.filterActive]}><Text style={[styles.filterText,days===d&&styles.filterTextActive]}>{d===365?'12 meses':`${d} dias`}</Text></AnimatedPressable>)}</View>
 <Text style={styles.filterLabel}>Unidade</Text><View style={styles.filters}><AnimatedPressable onPress={()=>setUnitId(null)} style={[styles.filter,!unitId&&styles.filterActive]}><Text style={[styles.filterText,!unitId&&styles.filterTextActive]}>Todas</Text></AnimatedPressable>{filters.units.map(u=><AnimatedPressable key={u.id} onPress={()=>setUnitId(u.id)} style={[styles.filter,unitId===u.id&&styles.filterActive]}><Text style={[styles.filterText,unitId===u.id&&styles.filterTextActive]}>{u.name}</Text></AnimatedPressable>)}</View>
 <Text style={styles.filterLabel}>Setor</Text><View style={styles.filters}><AnimatedPressable onPress={()=>setSector(null)} style={[styles.filter,!sector&&styles.filterActive]}><Text style={[styles.filterText,!sector&&styles.filterTextActive]}>Todos</Text></AnimatedPressable>{filters.sectors.map(s=><AnimatedPressable key={s} onPress={()=>setSector(s)} style={[styles.filter,sector===s&&styles.filterActive]}><Text style={[styles.filterText,sector===s&&styles.filterTextActive]}>{s}</Text></AnimatedPressable>)}</View>
 <Text style={styles.applied}>Visualizando: {selectedUnit} · {sector??'Todos os setores'} · {days===365?'12 meses':`${days} dias`}</Text></View>
 {loading?<View style={styles.loading}><ActivityIndicator color={colors.primary}/><Text style={styles.empty}>Atualizando indicadores...</Text></View>:<>
 <View style={styles.stats}><StatCard label="Trabalhadores ativos" value={String(data?.active_workers??0)} icon="people-outline"/><StatCard label="Agendamentos" value={String(data?.total_bookings??0)} icon="calendar-outline"/><StatCard label="Taxa de presença" value={`${data?.attendance_rate??0}%`} icon="checkmark-circle-outline"/><StatCard label="Taxa de ausência" value={`${data?.absence_rate??0}%`} icon="close-circle-outline"/><StatCard label="Acessos a conteúdos" value={String(data?.content_views??0)} icon="library-outline"/><StatCard label="Campanhas" value={String(data?.campaign_participants??0)} icon="megaphone-outline"/></View>
 <View style={[styles.summary,mobile&&styles.summaryMobile]}><View style={styles.summaryItem}><Text style={styles.summaryValue}>{data?.units_count??0}</Text><Text style={styles.summaryLabel}>unidades representadas</Text></View><View style={styles.summaryItem}><Text style={styles.summaryValue}>{data?.sectors_count??0}</Text><Text style={styles.summaryLabel}>setores representados</Text></View><View style={styles.summaryItem}><Text style={styles.summaryValue}>{data?.wellbeing_responses??0}</Text><Text style={styles.summaryLabel}>check-ins agregados</Text></View><View style={styles.summaryItem}><Text style={styles.summaryValue}>{data?.wellbeing_average??'—'}</Text><Text style={styles.summaryLabel}>média de humor*</Text></View></View>
 <View style={styles.grid}><MetricBars title="Trabalhadores por setor" items={data?.workers_by_sector??[]}/><MetricBars title="Agendamentos por setor" items={data?.bookings_by_sector??[]}/><MetricBars title="Presença por setor" items={data?.attendance_by_sector??[]} suffix="%"/><MetricBars title="Procura por categoria" items={data?.bookings_by_category??[]}/></View>
 </>}
 <View style={styles.privacy}><Text style={styles.privacyTitle}>Privacidade da gestão</Text><Text style={styles.privacyText}>O painel trabalha com agregados. Não exibe respostas individuais de bem-estar, justificativas de ausência, nomes de trabalhadores ou outros dados sensíveis. *A média de humor só é exibida quando há pelo menos 5 respostas no recorte.</Text></View>
 </Page>;
}
const styles=StyleSheet.create({filterPanel:{gap:8,padding:15,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,backgroundColor:colors.surface},filterTitle:{fontSize:16,fontWeight:'900',color:colors.text},filterLabel:{fontSize:10,fontWeight:'900',color:colors.textMuted,textTransform:'uppercase',letterSpacing:.6,marginTop:3},filters:{flexDirection:'row',gap:7,flexWrap:'wrap'},filter:{paddingHorizontal:11,paddingVertical:8,borderWidth:1,borderColor:colors.border,borderRadius:radii.pill,backgroundColor:colors.surface},filterActive:{backgroundColor:colors.primary,borderColor:colors.primary},filterText:{fontSize:10,fontWeight:'800',color:colors.textMuted},filterTextActive:{color:'#fff'},applied:{fontSize:10,color:colors.primaryDark,fontWeight:'800',marginTop:3},loading:{padding:30,alignItems:'center',gap:9},stats:{flexDirection:'row',flexWrap:'wrap',gap:12},summary:{flexDirection:'row',gap:10},summaryMobile:{flexWrap:'wrap'},summaryItem:{flex:1,minWidth:150,padding:14,borderRadius:radii.lg,backgroundColor:colors.primarySofter,borderWidth:1,borderColor:colors.border},summaryValue:{fontSize:25,fontWeight:'900',color:colors.primary},summaryLabel:{fontSize:10,color:colors.textMuted,marginTop:3},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{flex:1,minWidth:300,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:18,gap:12},cardTitle:{fontWeight:'900',color:colors.text,fontSize:16},barRow:{flexDirection:'row',alignItems:'center',gap:8},barLabel:{width:104,fontSize:10,color:colors.textMuted},barTrack:{flex:1,height:9,borderRadius:99,backgroundColor:colors.primarySoft,overflow:'hidden'},barFill:{height:'100%',backgroundColor:colors.primary,borderRadius:99},barValue:{width:44,textAlign:'right',fontSize:10,fontWeight:'900',color:colors.text},empty:{fontSize:11,color:colors.textMuted},privacy:{padding:15,borderRadius:radii.lg,backgroundColor:colors.primarySofter,borderWidth:1,borderColor:colors.border},privacyTitle:{fontWeight:'900',color:colors.primaryDark},privacyText:{fontSize:11,lineHeight:17,color:colors.textMuted,marginTop:4}});
