import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable } from '@/components/AnimatedPressable';
import { Page } from '@/components/Page';
import { SectionTitle } from '@/components/SectionTitle';
import { colors, radii } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { getBookings, justifyAbsence } from '@/lib/repository';
import { AbsenceReason, Booking } from '@/types/domain';

const reasons:{key:AbsenceReason;label:string}[]=[{key:'work_demand',label:'Demanda de trabalho'},{key:'schedule_conflict',label:'Conflito de horário'},{key:'personal',label:'Motivo pessoal'},{key:'other',label:'Outro'}];
export default function ProfileScreen(){
 const {profile,signOut,isDemo}=useAuth(); const [bookings,setBookings]=useState<Booking[]>([]); const [open,setOpen]=useState<string|null>(null);
 useEffect(()=>{getBookings().then(setBookings)},[]);
 async function leave(){await signOut();router.replace('/')}
 async function justify(id:string,reason:AbsenceReason){try{await justifyAbsence(id,reason);Alert.alert('Justificativa registrada','A categoria ficará disponível somente para você, o profissional responsável e a administração operacional.');setOpen(null);setBookings(await getBookings())}catch(e:any){Alert.alert('Erro',e.message)}}
 return <Page narrow><SectionTitle title="Perfil" subtitle="Seus dados de acesso, histórico e privacidade."/><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{profile?.full_name?.slice(0,1).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={styles.name}>{profile?.full_name}</Text><Text style={styles.meta}>{profile?.unit_name}</Text><Text style={styles.meta}>{profile?.organization_name}</Text></View><View style={styles.role}><Text style={styles.roleText}>Trabalhador</Text></View></View>
 <Text style={styles.heading}>Meus agendamentos</Text><View style={styles.list}>{bookings.map(b=><View key={b.id} style={styles.booking}><View style={{flex:1,minWidth:180}}><Text style={styles.bookingTitle}>{b.service_title}</Text><Text style={styles.bookingMeta}>{new Date(b.starts_at).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})} · {b.location}</Text><Text style={styles.bookingStatus}>Status: {b.status==='attended'?'Presente':b.status==='no_show'?'Ausente':b.status==='cancelled'?'Cancelado':'Confirmado'}</Text>{b.absence_reason?<Text style={styles.justified}>Justificativa registrada</Text>:null}</View>{b.status==='no_show'&&!b.absence_reason?<AnimatedPressable onPress={()=>setOpen(open===b.id?null:b.id)} style={styles.justifyBtn}><Text style={styles.justifyText}>Justificar</Text></AnimatedPressable>:null}{open===b.id?<View style={styles.reasonBox}>{reasons.map(r=><AnimatedPressable key={r.key} onPress={()=>justify(b.id,r.key)} style={styles.reason}><Text style={styles.reasonText}>{r.label}</Text></AnimatedPressable>)}</View>:null}</View>)}{bookings.length===0?<Text style={styles.empty}>Nenhum agendamento ainda.</Text>:null}</View>
 <View style={styles.item}><View style={styles.itemIcon}><Ionicons name="shield-checkmark-outline" size={21} color={colors.primary}/></View><View style={{flex:1}}><Text style={styles.itemTitle}>Privacidade e dados</Text><Text style={styles.itemText}>O MVP evita peso, IMC, dieta, diagnóstico e texto livre em justificativas. A gestão recebe somente indicadores agregados.</Text></View></View>{isDemo&&<View style={styles.demo}><Ionicons name="flask-outline" size={18} color="#9B6500"/><Text style={styles.demoText}>Modo de demonstração: nenhum dado real é persistido.</Text></View>}<AnimatedPressable onPress={leave} style={styles.logout}><Ionicons name="log-out-outline" size={20} color={colors.danger}/><Text style={styles.logoutText}>Sair</Text></AnimatedPressable></Page>
}
const styles=StyleSheet.create({profile:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:18,flexDirection:'row',flexWrap:'wrap',gap:12,alignItems:'center'},avatar:{width:58,height:58,borderRadius:20,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontSize:24,fontWeight:'900'},name:{color:colors.text,fontSize:18,fontWeight:'900'},meta:{color:colors.textMuted,fontSize:12,marginTop:2},role:{backgroundColor:colors.primarySoft,borderRadius:radii.pill,paddingHorizontal:10,paddingVertical:6},roleText:{color:colors.primaryDark,fontSize:11,fontWeight:'900'},heading:{fontSize:18,fontWeight:'900',color:colors.text},list:{gap:9},booking:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:14,flexDirection:'row',flexWrap:'wrap',gap:9,alignItems:'center'},bookingTitle:{fontWeight:'900',color:colors.text},bookingMeta:{fontSize:11,color:colors.textMuted,marginTop:3},bookingStatus:{fontSize:11,color:colors.text,marginTop:5,fontWeight:'700'},justified:{fontSize:10,color:colors.primary,marginTop:3,fontWeight:'900'},justifyBtn:{paddingHorizontal:11,paddingVertical:8,borderRadius:radii.pill,backgroundColor:colors.accentSoft},justifyText:{fontSize:10,fontWeight:'900',color:'#855800'},reasonBox:{width:'100%',flexDirection:'row',flexWrap:'wrap',gap:6,paddingTop:4},reason:{paddingHorizontal:9,paddingVertical:7,borderRadius:radii.pill,backgroundColor:colors.background,borderWidth:1,borderColor:colors.border},reasonText:{fontSize:9,fontWeight:'800',color:colors.textMuted},empty:{color:colors.textMuted,textAlign:'center',padding:18},item:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:16,flexDirection:'row',gap:12,alignItems:'center'},itemIcon:{width:43,height:43,borderRadius:14,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},itemTitle:{color:colors.text,fontSize:14,fontWeight:'900'},itemText:{color:colors.textMuted,fontSize:11,lineHeight:16,marginTop:3},demo:{flexDirection:'row',gap:8,backgroundColor:colors.accentSoft,padding:13,borderRadius:radii.md},demoText:{flex:1,color:'#7A5600',fontSize:11,lineHeight:16},logout:{borderRadius:radii.md,borderWidth:1,borderColor:'#F3C9C9',minHeight:48,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,backgroundColor:colors.dangerSoft},logoutText:{color:colors.danger,fontWeight:'900'}});
