import { Ionicons } from '@expo/vector-icons';
import React, { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable } from '@/components/AnimatedPressable';
import { Page } from '@/components/Page';
import { SectionTitle } from '@/components/SectionTitle';
import { colors, radii } from '@/constants/theme';
import { getProfessionalAttendees, getProfessionalServices, setAttendance } from '@/lib/repository';
import { HealthService, ProfessionalAttendee } from '@/types/domain';

const reasonLabel:any={work_demand:'Demanda de trabalho',schedule_conflict:'Conflito de horário',personal:'Motivo pessoal',other:'Outro'};
export default function ProfessionalAttendance(){
 const [services,setServices]=useState<HealthService[]>([]);const [slot,setSlot]=useState('');const [attendees,setAttendees]=useState<ProfessionalAttendee[]>([]);
 useEffect(()=>{getProfessionalServices().then(setServices);},[]);
 async function choose(id:string){setSlot(id);setAttendees(await getProfessionalAttendees(id));}
 async function mark(id:string,status:'attended'|'no_show'|'confirmed'){try{await setAttendance(id,status);if(slot)setAttendees(await getProfessionalAttendees(slot));}catch(e:any){Alert.alert('Erro',e.message)}}
 const slots=services.flatMap(s=>s.slots.map(sl=>({...sl,service_title:s.title}))).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));
 return <Page><SectionTitle title="Presenças e justificativas" subtitle="Acesse somente participantes das atividades sob sua responsabilidade."/><View style={styles.slotPicker}>{slots.map(s=><AnimatedPressable key={s.id} onPress={()=>choose(s.id)} style={[styles.slotChip,slot===s.id&&styles.slotChipActive]}><Text style={[styles.slotChipText,slot===s.id&&styles.slotChipTextActive]}>{s.service_title} · {new Date(s.starts_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</Text></AnimatedPressable>)}</View>
 {!slot?<View style={styles.empty}><Ionicons name="people-outline" size={34} color={colors.textMuted}/><Text style={styles.emptyTitle}>Selecione uma atividade</Text><Text style={styles.emptyText}>A lista de participantes aparecerá aqui.</Text></View>:<View style={styles.list}>{attendees.map(a=><View key={a.booking_id} style={styles.row}><View style={styles.avatar}><Text style={styles.avatarText}>{a.full_name.slice(0,1)}</Text></View><View style={{flex:1,minWidth:170}}><Text style={styles.name}>{a.full_name}</Text><Text style={styles.meta}>Status: {a.booking_status==='attended'?'Presente':a.booking_status==='no_show'?'Ausente':'Confirmado'}</Text>{a.absence_reason?<Text style={styles.reason}>Justificativa: {reasonLabel[a.absence_reason]}</Text>:null}</View><View style={styles.actions}><AnimatedPressable onPress={()=>mark(a.booking_id,'attended')} style={[styles.mini,styles.present]}><Text style={styles.presentText}>Presente</Text></AnimatedPressable><AnimatedPressable onPress={()=>mark(a.booking_id,'no_show')} style={[styles.mini,styles.absent]}><Text style={styles.absentText}>Faltou</Text></AnimatedPressable></View></View>)}{attendees.length===0&&<Text style={styles.emptyText}>Ainda não há participantes neste horário.</Text>}</View>}
 <View style={styles.notice}><Ionicons name="shield-checkmark-outline" size={18} color={colors.primary}/><Text style={styles.noticeText}>Justificativas do MVP usam categorias sem texto livre para reduzir a coleta de informações sensíveis. A gestão não recebe estes dados individualizados.</Text></View>
 </Page>;
}
const styles=StyleSheet.create({slotPicker:{flexDirection:'row',flexWrap:'wrap',gap:8},slotChip:{borderWidth:1,borderColor:colors.border,borderRadius:radii.pill,paddingHorizontal:11,paddingVertical:9,backgroundColor:colors.surface},slotChipActive:{backgroundColor:colors.primary,borderColor:colors.primary},slotChipText:{fontSize:11,fontWeight:'800',color:colors.textMuted},slotChipTextActive:{color:'#fff'},empty:{padding:50,alignItems:'center',gap:7},emptyTitle:{fontWeight:'900',color:colors.text},emptyText:{color:colors.textMuted,fontSize:12,textAlign:'center'},list:{gap:9},row:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:11,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:13},avatar:{width:42,height:42,borderRadius:14,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},avatarText:{fontWeight:'900',color:colors.primaryDark},name:{fontWeight:'900',color:colors.text},meta:{fontSize:11,color:colors.textMuted,marginTop:2},reason:{fontSize:11,color:'#8A5A00',marginTop:3},actions:{flexDirection:'row',gap:6,flexWrap:'wrap'},mini:{paddingHorizontal:10,paddingVertical:8,borderRadius:radii.pill},present:{backgroundColor:colors.primarySoft},absent:{backgroundColor:colors.dangerSoft},presentText:{fontSize:10,fontWeight:'900',color:colors.primaryDark},absentText:{fontSize:10,fontWeight:'900',color:colors.danger},notice:{flexDirection:'row',gap:8,padding:13,borderRadius:radii.md,backgroundColor:colors.primarySofter},noticeText:{flex:1,fontSize:11,lineHeight:17,color:colors.textMuted}});
